const express = require('express');
const router = express.Router();
const db = require('../config/db');

// Metadata for all available reports
const REPORTS = [
  {
    id: 'q1',
    category: 'Basic Profiles',
    title: 'Patient User Profiles',
    description: 'Full patient profile with linked user account information.',
    sql: `
      SELECT p.patient_id, p.name, p.phone, p.dob, p.gender, p.blood_group, u.email, u.created_at AS registered_on
      FROM patients p
      LEFT JOIN users u ON u.user_id = p.user_id
      ORDER BY p.patient_id
    `
  },
  {
    id: 'q2',
    category: 'Operational',
    title: 'Doctor Directory',
    description: 'List of all doctors with department, specialization, and consultation fees.',
    sql: `
      SELECT d.doctor_id, u.name AS doctor_name, dept.dept_name, d.specialization, d.consultation_fee, d.experience_years
      FROM doctors d
      JOIN users u ON u.user_id = d.user_id
      JOIN departments dept ON dept.dept_id = d.dept_id
      ORDER BY d.consultation_fee DESC
    `
  },
  {
    id: 'q3',
    category: 'Operational',
    title: "Today's Appointments",
    description: 'All scheduled appointments for the current date.',
    sql: `
      SELECT a.appt_id, a.token_no, p.name AS patient_name, u.name AS doctor_name, dept.dept_name, a.appt_time, a.status
      FROM appointments a
      JOIN patients p ON p.patient_id = a.patient_id
      JOIN doctors d ON d.doctor_id = a.doctor_id
      JOIN users u ON u.user_id = d.user_id
      JOIN departments dept ON dept.dept_id = d.dept_id
      WHERE a.appt_date = CURRENT_DATE
      ORDER BY a.appt_time
    `
  },
  {
    id: 'q4',
    category: 'Inpatient',
    title: 'Active Admissions Details',
    description: 'List of currently admitted patients with ward, bed, and accrued charges.',
    sql: `
      SELECT a.admission_id, p.name AS patient_name, u.name AS doctor_name, w.ward_name, w.ward_type, b.bed_number, 
             w.daily_rate, a.admit_date, DATEDIFF(CURRENT_DATE, DATE(a.admit_date)) AS days_admitted,
             DATEDIFF(CURRENT_DATE, DATE(a.admit_date)) * w.daily_rate AS accrued_bed_charge
      FROM admissions a
      JOIN patients p ON p.patient_id = a.patient_id
      JOIN doctors d ON d.doctor_id = a.doctor_id
      JOIN users u ON u.user_id = d.user_id
      JOIN beds b ON b.bed_id = a.bed_id
      JOIN wards w ON w.ward_id = b.ward_id
      WHERE a.status = 'admitted'
    `
  },
  {
    id: 'q7',
    category: 'Financials',
    title: 'Revenue by Charge Type',
    description: 'Breakdown of total revenue generated by various service categories.',
    sql: `
      SELECT bd.charge_type, COUNT(DISTINCT bd.bill_id) AS num_bills, COUNT(bd.detail_id) AS num_line_items,
             SUM(bd.amount) AS total_revenue, AVG(bd.amount) AS avg_charge, MAX(bd.amount) AS max_charge
      FROM bill_details bd
      GROUP BY bd.charge_type
      ORDER BY total_revenue DESC
    `
  },
  {
    id: 'q8',
    category: 'Financials',
    title: 'Department Performance',
    description: 'Appointment counts, completion rates, and revenue per department.',
    sql: `
      SELECT dept.dept_name, COUNT(a.appt_id) AS total_appointments,
             COUNT(CASE WHEN a.status = 'completed' THEN 1 END) AS completed,
             COUNT(CASE WHEN a.status = 'cancelled' THEN 1 END) AS cancelled,
             SUM(d.consultation_fee) AS total_fee_earned
      FROM appointments a
      JOIN doctors d ON d.doctor_id = a.doctor_id
      JOIN departments dept ON dept.dept_id = d.dept_id
      GROUP BY dept.dept_name
      ORDER BY total_appointments DESC
    `
  },
  {
    id: 'q9',
    category: 'Financials',
    title: 'Monthly Revenue Growth',
    description: 'Month-over-month summary of billing, collections, and outstanding balances.',
    sql: `
      SELECT DATE_FORMAT(b.bill_date, '%Y-%m-01') AS month, COUNT(b.bill_id) AS bills_generated,
             SUM(b.total_amount) AS gross_revenue, SUM(COALESCE(py.paid,0)) AS amount_collected,
             SUM(b.total_amount) - SUM(COALESCE(py.paid,0)) AS outstanding
      FROM bills b
      LEFT JOIN (SELECT bill_id, SUM(amount_paid) AS paid FROM payments GROUP BY bill_id) py ON py.bill_id = b.bill_id
      WHERE b.status != 'cancelled'
      GROUP BY month
      ORDER BY month DESC
    `
  },
  {
    id: 'q10',
    category: 'Pharmacy',
    title: 'Highly Prescribed Medicines',
    description: 'Top 5 medicines most frequently prescribed by doctors.',
    sql: `
      SELECT m.medicine_name, m.category, COUNT(pi.item_id) AS times_prescribed,
             SUM(pi.quantity) AS total_units_dispensed, SUM(pi.quantity * m.price_per_unit) AS total_revenue
      FROM prescription_items pi
      JOIN medicines m ON m.medicine_id = pi.medicine_id
      GROUP BY m.medicine_id, m.medicine_name, m.category
      ORDER BY times_prescribed DESC
      LIMIT 5
    `
  },
  {
    id: 'q11',
    category: 'Patient Care',
    title: 'Chronic Patients',
    description: 'Patients who have been admitted to the hospital more than once.',
    sql: `
      SELECT p.patient_id, p.name, p.phone, admission_count
      FROM patients p
      JOIN (SELECT patient_id, COUNT(*) AS admission_count FROM admissions GROUP BY patient_id HAVING COUNT(*) > 1) 
      repeated ON repeated.patient_id = p.patient_id
      ORDER BY admission_count DESC
    `
  },
  {
    id: 'q12',
    category: 'Operational',
    title: 'Premium Doctors',
    description: 'Doctors whose consultation fee is above their department average.',
    sql: `
      SELECT u.name AS doctor_name, d.specialization, d.consultation_fee, dept.dept_name, dept_avg.avg_fee AS department_average
      FROM doctors d
      JOIN users u ON u.user_id = d.user_id
      JOIN departments dept ON dept.dept_id = d.dept_id
      JOIN (SELECT dept_id, AVG(consultation_fee) AS avg_fee FROM doctors GROUP BY dept_id) 
      dept_avg ON dept_avg.dept_id = d.dept_id
      WHERE d.consultation_fee > dept_avg.avg_fee
    `
  },
  {
    id: 'q13',
    category: 'Labs',
    title: 'Pending Lab Tests',
    description: 'Patients currently waiting for lab test results.',
    sql: `
      SELECT p.patient_id, p.name, p.phone
      FROM patients p
      WHERE EXISTS (SELECT 1 FROM lab_orders lo WHERE lo.patient_id = p.patient_id AND lo.status IN ('pending','processing'))
    `
  },
  {
    id: 'q14',
    category: 'Financials',
    title: 'Above Average Bills',
    description: 'Bills that exceed the overall average bill amount.',
    sql: `
      SELECT b.bill_id, p.name AS patient_name, b.total_amount, b.bill_date, b.status
      FROM bills b
      JOIN patients p ON p.patient_id = b.patient_id
      WHERE b.total_amount > (SELECT AVG(total_amount) FROM bills WHERE status != 'cancelled')
      ORDER BY b.total_amount DESC
    `
  },
  {
    id: 'q15',
    category: 'Financials',
    title: 'Patient Ledger Summary',
    description: 'Total billed, paid, and outstanding amounts for every patient.',
    sql: `
      SELECT p.patient_id, p.name, COUNT(bs.bill_id) AS total_bills, SUM(bs.total_amount) AS total_billed,
             SUM(bs.paid_amount) AS total_paid, SUM(bs.total_amount - bs.paid_amount) AS total_outstanding
      FROM patients p
      JOIN (
        SELECT b.patient_id, b.bill_id, b.total_amount, COALESCE(SUM(py.amount_paid), 0) AS paid_amount
        FROM bills b
        LEFT JOIN payments py ON py.bill_id = b.bill_id
        GROUP BY b.bill_id, b.patient_id, b.total_amount
      ) bs ON bs.patient_id = p.patient_id
      GROUP BY p.patient_id, p.name
      ORDER BY total_outstanding DESC
    `
  },
  {
    id: 'q16',
    category: 'Inpatient',
    title: 'Ward Occupancy Analysis',
    description: 'Real-time bed occupancy percentage across all hospital wards.',
    sql: `
      SELECT wc.ward_name, wc.ward_type, wc.total_beds, COALESCE(o.occupied_beds, 0) AS occupied_beds,
             wc.total_beds - COALESCE(o.occupied_beds, 0) AS available_beds,
             ROUND(COALESCE(o.occupied_beds,0) / wc.total_beds * 100, 1) AS occupancy_pct
      FROM (
        SELECT w.ward_id, w.ward_name, w.ward_type, COUNT(b.bed_id) AS total_beds
        FROM wards w
        JOIN beds b ON b.ward_id = w.ward_id
        GROUP BY w.ward_id, w.ward_name, w.ward_type
      ) wc
      LEFT JOIN (SELECT b.ward_id, COUNT(*) AS occupied_beds FROM beds b WHERE b.status = 'occupied' GROUP BY b.ward_id) 
      o ON o.ward_id = wc.ward_id
      ORDER BY occupancy_pct DESC
    `
  },
  {
    id: 'q17',
    category: 'Financials',
    title: 'Billing Audit Trail',
    description: 'Component-wise breakdown of all generated bills.',
    sql: `
      SELECT b.bill_id, p.name AS patient_name, 
             MAX(CASE WHEN c.charge_type = 'doctor' THEN c.subtotal END) AS doctor_fee,
             MAX(CASE WHEN c.charge_type = 'lab' THEN c.subtotal END) AS lab_charges,
             MAX(CASE WHEN c.charge_type = 'bed' THEN c.subtotal END) AS bed_charges,
             MAX(CASE WHEN c.charge_type = 'pharmacy' THEN c.subtotal END) AS pharmacy_charges,
             b.total_amount
      FROM bills b
      JOIN patients p ON p.patient_id = b.patient_id
      LEFT JOIN (SELECT bill_id, charge_type, SUM(amount) AS subtotal FROM bill_details GROUP BY bill_id, charge_type) 
      c ON c.bill_id = b.bill_id
      GROUP BY b.bill_id, p.name, b.total_amount
      ORDER BY total_amount DESC
    `
  },
  {
    id: 'q21',
    category: 'Trends',
    title: 'Billing Quartile Analysis',
    description: 'Classification of patients into quartiles based on their total billing.',
    sql: `
      SELECT ranked.name, ranked.total_billed,
             CASE
               WHEN ranked.rank_value <= CEIL(q.total_count * 0.25) THEN 'Top 25%'
               WHEN ranked.rank_value <= CEIL(q.total_count * 0.50) THEN 'Top 50%'
               WHEN ranked.rank_value <= CEIL(q.total_count * 0.75) THEN 'Top 75%'
               ELSE 'Bottom 25%'
             END AS billing_segment
      FROM (
        SELECT x.name, x.total_billed,
               (SELECT COUNT(*)
                FROM (
                  SELECT y.patient_id, SUM(y.total_amount) AS total_billed
                  FROM bills y
                  GROUP BY y.patient_id
                ) z
                WHERE z.total_billed > x.total_billed
               ) + 1 AS rank_value
        FROM (
          SELECT p.patient_id, p.name, SUM(b.total_amount) AS total_billed
          FROM bills b
          JOIN patients p ON p.patient_id = b.patient_id
          GROUP BY p.patient_id, p.name
        ) x
      ) ranked
      CROSS JOIN (
        SELECT COUNT(DISTINCT patient_id) AS total_count FROM bills
      ) q
      ORDER BY ranked.total_billed DESC
    `
  },
  {
    id: 'q22',
    category: 'Patient Care',
    title: 'Patient Retention Stats',
    description: 'First visit, latest visit, and total visits for all patients.',
    sql: `
      SELECT p.name AS patient_name, MIN(a.appt_date) AS first_appointment,
             MAX(a.appt_date) AS latest_appointment, COUNT(a.appt_id) AS total_visits
      FROM appointments a
      JOIN patients p ON p.patient_id = a.patient_id
      WHERE a.status = 'completed'
      GROUP BY p.patient_id, p.name
    `
  },
  {
    id: 'q23',
    category: 'Financials',
    title: 'Payment Risk Assessment',
    description: 'Identifies patients with high outstanding balances.',
    sql: `
      SELECT p.name, b.bill_id, b.total_amount, COALESCE(SUM(py.amount_paid), 0) AS paid, 
             b.total_amount - COALESCE(SUM(py.amount_paid), 0) AS balance,
             CASE
                 WHEN b.status = 'paid' THEN 'Cleared'
                 WHEN b.total_amount - COALESCE(SUM(py.amount_paid),0) > 10000 THEN 'Critical Risk'
                 WHEN b.total_amount - COALESCE(SUM(py.amount_paid),0) > 5000 THEN 'Medium Risk'
                 ELSE 'Low Risk'
             END AS risk_status
      FROM bills b
      JOIN patients p ON p.patient_id = b.patient_id
      LEFT JOIN payments py ON py.bill_id = b.bill_id
      GROUP BY b.bill_id, p.name, b.total_amount, b.status
      ORDER BY balance DESC
    `
  },
  {
    id: 'q24',
    category: 'Pharmacy',
    title: 'Medicine Inventory Health',
    description: 'Current stock levels vs reorder levels for all medicines.',
    sql: `
      SELECT medicine_name, category, stock_quantity, reorder_level,
             CASE
                 WHEN stock_quantity = 0 THEN 'OUT OF STOCK'
                 WHEN stock_quantity < reorder_level THEN 'CRITICAL'
                 WHEN stock_quantity < reorder_level * 2 THEN 'LOW'
                 ELSE 'ADEQUATE'
             END AS stock_status
      FROM medicines
      ORDER BY stock_quantity ASC
    `
  },
  {
    id: 'q25',
    category: 'Labs',
    title: 'Lab Turnaround Time (TAT)',
    description: 'Analysis of lab test completion speeds vs expected times.',
    sql: `
      SELECT p.name AS patient_name, lt.test_name, lo.ordered_date, lo.result_date,
             COALESCE(DATEDIFF(lo.result_date, lo.ordered_date), 0) AS actual_days,
             lt.turnaround_hours / 24 AS expected_days,
             CASE
                 WHEN lo.result_date IS NULL THEN 'Pending'
                 WHEN DATEDIFF(lo.result_date, lo.ordered_date) <= lt.turnaround_hours/24 THEN 'On Time'
                 ELSE 'Delayed'
             END AS tat_status
      FROM lab_orders lo
      JOIN patients p ON p.patient_id = lo.patient_id
      JOIN lab_tests lt ON lt.test_id = lo.test_id
    `
  },
  {
    id: 'q27',
    category: 'Patient Care',
    title: 'Admissions with No Bills',
    description: 'Audit report finding admitted patients who haven\'t been billed yet.',
    sql: `
      SELECT p.patient_id, p.name FROM patients p
      WHERE p.patient_id IN (SELECT patient_id FROM admissions)
      AND p.patient_id NOT IN (SELECT patient_id FROM bills)
    `
  },
  {
    id: 'q31',
    category: 'Operational',
    title: 'Doctor Performance Index',
    description: 'Comprehensive report on doctor appointment volume and estimated revenue.',
    sql: `
      SELECT u.name AS doctor_name, dept.dept_name, COUNT(a.appt_id) AS total_appointments,
             COUNT(CASE WHEN a.status='completed' THEN 1 END) AS completed,
             ROUND(COUNT(CASE WHEN a.status='completed' THEN 1 END) / NULLIF(COUNT(a.appt_id),0) * 100, 1) AS completion_pct,
             COUNT(CASE WHEN a.status='completed' THEN 1 END) * d.consultation_fee AS est_revenue
      FROM doctors d
      JOIN users u ON u.user_id = d.user_id
      JOIN departments dept ON dept.dept_id = d.dept_id
      LEFT JOIN appointments a ON a.doctor_id = d.doctor_id
      GROUP BY d.doctor_id, u.name, dept.dept_name, d.consultation_fee
      ORDER BY est_revenue DESC
    `
  },
  {
    id: 'q32',
    category: 'Patient Care',
    title: 'Patient 360 View',
    description: 'Consolidated view of all patient interactions, tests, and financial state.',
    sql: `
      SELECT p.patient_id, p.name, p.blood_group,
             COALESCE(ac.cnt, 0) AS appointments, COALESCE(adc.cnt, 0) AS admissions,
             COALESCE(lc.cnt, 0) AS lab_tests, COALESCE(bt.billed, 0) AS total_billed,
             COALESCE(bt.billed, 0) - COALESCE(bt.paid, 0) AS balance
      FROM patients p
      LEFT JOIN (SELECT patient_id, COUNT(*) AS cnt FROM appointments GROUP BY patient_id) ac ON ac.patient_id = p.patient_id
      LEFT JOIN (SELECT patient_id, COUNT(*) AS cnt FROM admissions GROUP BY patient_id) adc ON adc.patient_id = p.patient_id
      LEFT JOIN (SELECT patient_id, COUNT(*) AS cnt FROM lab_orders GROUP BY patient_id) lc ON lc.patient_id = p.patient_id
      LEFT JOIN (
        SELECT b.patient_id, SUM(b.total_amount) AS billed, SUM(COALESCE(py.paid,0)) AS paid
        FROM bills b
        LEFT JOIN (SELECT bill_id, SUM(amount_paid) AS paid FROM payments GROUP BY bill_id) py ON py.bill_id = b.bill_id
        GROUP BY b.patient_id
      ) bt ON bt.patient_id = p.patient_id
      ORDER BY balance DESC
    `
  },
  {
    id: 'q33',
    category: 'Inpatient',
    title: 'Long-stay Patients',
    description: 'Identifies patients with the longest current hospital stay.',
    sql: `
      SELECT b.bed_number, w.ward_name, p.name AS current_patient, a.admit_date,
             DATEDIFF(CURRENT_DATE, DATE(a.admit_date)) AS days_occupied
      FROM admissions a
      JOIN beds b ON b.bed_id = a.bed_id
      JOIN wards w ON w.ward_id = b.ward_id
      JOIN patients p ON p.patient_id = a.patient_id
      WHERE a.status = 'admitted'
      ORDER BY days_occupied DESC
    `
  },
  {
    id: 'q34',
    category: 'Trends',
    title: 'Revenue Composition per Patient',
    description: 'Multi-column distribution of charges (Doctor, Lab, Bed, etc.) for each patient.',
    sql: `
      SELECT p.name AS patient_name,
             SUM(CASE WHEN bd.charge_type = 'doctor' THEN bd.amount ELSE 0 END) AS doctor_charges,
             SUM(CASE WHEN bd.charge_type = 'lab' THEN bd.amount ELSE 0 END) AS lab_charges,
             SUM(CASE WHEN bd.charge_type = 'bed' THEN bd.amount ELSE 0 END) AS bed_charges,
             SUM(CASE WHEN bd.charge_type = 'pharmacy' THEN bd.amount ELSE 0 END) AS pharm_charges,
             SUM(bd.amount) AS grand_total
      FROM bills b
      JOIN patients p ON p.patient_id = b.patient_id
      JOIN bill_details bd ON bd.bill_id = b.bill_id
      GROUP BY p.patient_id, p.name
      ORDER BY grand_total DESC
    `
  },
  {
    id: 'b1',
    category: 'Operational',
    title: 'Real-time Bed Availability',
    description: 'Current snapshot of all available beds in the hospital.',
    sql: `
      SELECT w.ward_name, w.ward_type, w.daily_rate, b.bed_number, b.status
      FROM beds b
      JOIN wards w ON w.ward_id = b.ward_id
      WHERE b.status = 'available'
      ORDER BY w.daily_rate
    `
  },
  {
    id: 'b3',
    category: 'Financials',
    title: "Daily Revenue Snapshot",
    description: "Summary of payments collected today.",
    sql: `
      SELECT COALESCE(SUM(py.amount_paid), 0) AS total_collected, COUNT(py.payment_id) AS transactions, 
             MAX(py.amount_paid) AS largest_payment
      FROM payments py
      WHERE py.payment_date = CURRENT_DATE
    `
  },
  {
    id: 'q18',
    category: 'Analysis',
    title: 'Doctor Fee Ranking',
    description: 'Ranks doctors by consultation fee within each department.',
    sql: `
      SELECT dept.dept_name,
             u.name AS doctor_name,
             d.consultation_fee,
             (SELECT COUNT(*) + 1
              FROM doctors d2
              WHERE d2.dept_id = d.dept_id
                AND d2.consultation_fee > d.consultation_fee
             ) AS fee_rank
      FROM doctors d
      JOIN users u ON u.user_id = d.user_id
      JOIN departments dept ON dept.dept_id = d.dept_id
      ORDER BY dept.dept_name, fee_rank
    `
  },
  {
    id: 'q19',
    category: 'Analysis',
    title: 'Payment Running Totals',
    description: 'Cumulative payment history per bill.',
    sql: `
      SELECT p.payment_id, b.bill_id, pat.name AS patient_name, p.amount_paid, p.payment_date,
             (SELECT SUM(p2.amount_paid)
              FROM payments p2
              WHERE p2.bill_id = p.bill_id
                AND (p2.payment_date < p.payment_date OR (p2.payment_date = p.payment_date AND p2.payment_id <= p.payment_id))
             ) AS cumulative_paid,
             b.total_amount
      FROM payments p
      JOIN bills b ON b.bill_id = p.bill_id
      JOIN patients pat ON pat.patient_id = b.patient_id
      ORDER BY b.bill_id, p.payment_date, p.payment_id
    `
  },
  {
    id: 'q20',
    category: 'Analysis',
    title: 'Bill History Comparison',
    description: 'Compares each bill with the previous bill for the same patient.',
    sql: `
      SELECT b.bill_id, p.name AS patient_name, b.bill_date, b.total_amount,
             (SELECT bb.total_amount
              FROM bills bb
              WHERE bb.patient_id = b.patient_id
                AND (bb.bill_date < b.bill_date OR (bb.bill_date = b.bill_date AND bb.bill_id < b.bill_id))
              ORDER BY bb.bill_date DESC, bb.bill_id DESC
              LIMIT 1
             ) AS previous_bill,
             b.total_amount - (SELECT bb.total_amount
              FROM bills bb
              WHERE bb.patient_id = b.patient_id
                AND (bb.bill_date < b.bill_date OR (bb.bill_date = b.bill_date AND bb.bill_id < b.bill_id))
              ORDER BY bb.bill_date DESC, bb.bill_id DESC
              LIMIT 1
             ) AS diff
      FROM bills b
      JOIN patients p ON p.patient_id = b.patient_id
      ORDER BY p.name, b.bill_date
    `
  },
  {
    id: 'q26',
    category: 'Patient Care',
    title: 'Combined Patient Activity',
    description: 'Unified timeline of appointments and admissions.',
    sql: `
      SELECT 'Appointment' as type, appt_date as date, status FROM appointments
      UNION ALL
      SELECT 'Admission', admit_date, status FROM admissions
      ORDER BY date DESC
      LIMIT 100
    `
  },
  {
    id: 'q28',
    category: 'Financials',
    title: 'Revenue Rollup',
    description: 'Total revenue aggregated by department and doctor.',
    sql: `
      SELECT dept.dept_name, u.name as doctor_name, SUM(d.consultation_fee) as revenue
      FROM appointments a
      JOIN doctors d ON d.doctor_id = a.doctor_id
      JOIN users u ON u.user_id = d.user_id
      JOIN departments dept ON dept.dept_id = d.dept_id
      WHERE a.status = 'completed'
      GROUP BY dept.dept_name, u.name WITH ROLLUP
    `
  },
  {
    id: 'q29',
    category: 'Financials',
    title: 'Collection Efficiency',
    description: 'Analysis of billing vs actual collections.',
    sql: `
      SELECT b.bill_id, p.name as patient, b.total_amount, 
             COALESCE(SUM(py.amount_paid), 0) as paid,
             (COALESCE(SUM(py.amount_paid), 0) / b.total_amount) * 100 as collection_pct
      FROM bills b
      JOIN patients p ON p.patient_id = b.patient_id
      LEFT JOIN payments py ON py.bill_id = b.bill_id
      GROUP BY b.bill_id, p.name, b.total_amount
      HAVING collection_pct < 100
    `
  }
];

// GET /api/reports/list
router.get('/list', async (req, res) => {
  const metadata = REPORTS.map(({ id, category, title, description }) => ({ id, category, title, description }));
  res.json(metadata);
});

// GET /api/reports/run/:id
router.get('/run/:id', async (req, res) => {
  try {
    const report = REPORTS.find(r => r.id === req.params.id);
    if (!report) return res.status(404).json({ error: 'Report not found' });

    const { rows } = await db.query(report.sql);
    res.json({
        id: report.id,
        title: report.title,
        data: rows
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
